'フォロー機能です'
shinonome-inc/backend-final-assignment-HasegawaKota pull request #4
Opened 2022-07-10 09:25 UTC by HasegawaKota

2022-07-13 15:44 UTC, HasegawaKota commented
先日質問させていただいた件ですが、やはり自分でも解決できませんでした。それで別にホームでfollowとunfollowのhtmlをifで選択させなくても別の方法でいけるんじゃねと考えて、follower_listとfollowing_listに実装しました。

2022-07-16 04:28 UTC, TAK848 requested changes
お疲れ様です！！
コメントしたので確認お願いします！

全体へのコメントとして，
- base.htmlを編集するなどして，全ページに，「ログアウト時はログイン・サインアップ，ログイン時はログアウト・プロフィール，ホーム」のリンクをheaderでも何でも良いので貼っていただけると嬉しいです！
- テスト編集時は，PRのコメントにテスト成功のスクリーンショットなどを貼っておいていただけると助かります！

> 先日質問させていただいた件ですが、やはり自分でも解決できませんでした。それで別にホームでfollowとunfollowのhtmlをifで選択させなくても別の方法でいけるんじゃねと考えて、follower_listとfollowing_listに実装しました。

質問内容がわからないので詳細は分かりませんが，follower_listとfollowing_listに分けるのは良いと思います！！

2022-07-16 04:28 UTC, tak848 commented on accounts/models.py
> +    )
on_delete=models.CASCADEなのにnullを許容している理由はありますか？

2022-07-16 04:28 UTC, tak848 commented on accounts/models.py
> +        return "{} : {}".format(self.follower.username, self.following.username)
Python3.6以降はf文字列を使えるので，もし，特に理由がなければこちらを使いましょう！（他の箇所も同様）
```suggestion
        return f"{self.follower.username} : {self.following.username}"
```

2022-07-16 04:28 UTC, tak848 commented on accounts/views.py
>          return context
現状，以下の画像のように，ログイン中のユーザーの情報・ツイートと，urlのpkで指定したプロフィールの情報が混ざっています。
指定したプロフィールの人のTweetとProfileが表示されるように修正しましょう。

`/accounts/profile/1/`
<img width="654" alt="Screen Shot 2022-07-16 at 12 09 26" src="https://user-images.githubusercontent.com/41906969/179336938-1de7f696-c3e9-491d-850f-1879d9f8220f.png">

`/accounts/profile/2/`
<img width="660" alt="Screen Shot 2022-07-16 at 12 09 59" src="https://user-images.githubusercontent.com/41906969/179336954-f22e779c-8e90-4e50-a088-4d3c8d49fb22.png">

2022-07-16 04:28 UTC, tak848 commented on accounts/views.py
> +        )
名前が`xx_list`なのに実体がcountなので，命名を即したものに変えましょう！

2022-07-16 04:28 UTC, tak848 commented on accounts/views.py
> -        return Tweet.objects.all().select_related("user")
`get_queryset`を消したことにより，home.htmlの18-30行目でN+1が発生しています。

2022-07-16 04:28 UTC, tak848 commented on accounts/views.py
> +        context["tweets_list"] = Tweet.objects.select_related("user")
これ，使っていなさそうなんですが，ListViewのobject_listの取得（select_relatedがなくなっていてTweetだけを全取得している）とほぼ被って同じことをしています。
削除してよさそうです。

2022-07-16 04:28 UTC, tak848 commented on accounts/views.py
> +        ).filter(follower=self.request.user)
こちら使っていなさそうです…！

2022-07-16 04:28 UTC, tak848 commented on accounts/views.py
> +            messages.warning(request, "{}は存在しません".format(kwargs["username"]))
`get_object_or_404`を用いているので`User.DoesNotExist`がraiseされることはなさそうですが，いかがでしょう？

2022-07-16 04:28 UTC, tak848 commented on accounts/views.py
> +                messages.warning(request, "あなたは{}をフォローしました".format(following.username))
ちょい細かいけど，`warning`というよりは，`info`でも良いような気がしました

2022-07-16 04:28 UTC, tak848 commented on accounts/views.py
> +            follower = get_object_or_404(User, username=self.request.user.username)
```suggestion
            follower = self.request.user
```
で良いと思います！（self.request.userとfollowerは結局同義なので）

2022-07-16 04:28 UTC, tak848 commented on accounts/views.py
> +    context_object_name = "following_list"
TemplateViewには，modelやcontext_object_nameといったクラス変数はありません！（UnFollowも同様）
https://ccbv.co.uk/projects/Django/4.0/django.views.generic.base/TemplateView/

2022-07-16 04:28 UTC, tak848 commented on accounts/views.py
> +            return HttpResponseRedirect(reverse_lazy("accounts:home"))
reverse_lazyは，基本クラス変数（success_urlとか）などの，Djangoがファイル群を最初に一斉に読み込んだ時点で，reverseをすぐには実行することができないけど使用したい時に使います。
それ以外では`reverse`を使いましょう！（他も同様）

2022-07-16 04:28 UTC, tak848 commented on accounts/models.py
> +    )
コメントにあるように，影響範囲が広くて大変ですが，意味的にも`followee`（フォロー行為をされる人）と`follower`（フォローする人）にした方が良いです！
現状，「ん？」となってしまいます！

2022-07-16 04:28 UTC, tak848 commented on accounts/views.py
> +        ).filter(following=self.request.user)
N+1が回避できていてgoodです！
こっちでは`following`は使っていないので不要です！

2022-07-16 04:28 UTC, tak848 commented on templates/accounts/home.html
> +  <a href="{% url 'accounts:follow' tweet.user.username %}" class="btn btn-light">{{ tweet.user }}</a>
画面の自然な流れとしては，profile画面に飛ぶのが良いと思います。こちらに飛び，この画面にfollow，unfollowへの遷移を貼るようにしましょう！その時，followしているときはunfollowに飛ぶようにしましょう（現状ユーザー側にurlを推測して打たせないとunfollowできなくなってしまっている）！

2022-07-16 04:28 UTC, tak848 commented on accounts/views.py
> +        return context
（参考）もしListViewで書くと，例えば
```python
class FollowerListView(LoginRequiredMixin, ListView):
    model = FriendShip
    template_name = "accounts/follower_list.html"
    context_object_name = "follower_list"

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.select_related("follower").filter(following=self.request.user)
```
や
```python
class FollowerListView(LoginRequiredMixin, ListView):
    template_name = "accounts/follower_list.html"
    context_object_name = "follower_list"

    def get_queryset(self):
        return FriendShip.objects.select_related("follower").filter(following=self.request.user)
```
が同義になります。勉強の参考にしてください！

2022-07-16 04:28 UTC, TAK848 commented on templates/accounts/follower_list.html
> +<a href="{% url 'accounts:user_profile' pk=user.pk %}" class="btn btn-primary">プロフィール</a>
厳密には，`accounts:user_profile`のView，`UserProfileView`では`model=Profile`なので，
`user.profile.pk`が適切です（もし何らかの原因で連番が崩れると別のユーザーになってしまう）

2022-07-16 04:28 UTC, TAK848 commented on accounts/views.py
> +    template_name = "accounts/follow.html"
templateは不要です。（そういう意味では，TemplateViewでなくただのViewで良い）
確認画面は無しに，
HTML上でのフォロー，アンフォローの形式としては，formとしてmethodをPOST，actionをこのurlとし，type=submitのボタンを設置してこのViewに確認画面無しにアクセスするイメージ

2022-07-16 04:28 UTC, TAK848 commented on accounts/tests.py
> +        self.assertFalse(FriendShip.objects.filter(following=self.user1).exists())
テスト要件にもあるように，messageもテストしてあげてください！
https://qiita.com/i05tream/items/45cfd5e269cf8b2cef54

2022-07-16 04:28 UTC, TAK848 commented on accounts/tests.py
> +        )
使っていなそうです！

2022-07-16 22:05 UTC, HasegawaKota commented on accounts/views.py
> +        ).filter(following=self.request.user)
following=self.reequest.userをしないとフォロワー一覧が正しく出ません。

2022-07-16 22:08 UTC, TAK848 commented on accounts/views.py
> +        ).filter(following=self.request.user)
select_relatedの方です！

2022-07-16 22:40 UTC, HasegawaKota commented on accounts/views.py
> +        ).filter(following=self.request.user)
すみません。ありがとうございます！

2022-07-16 23:08 UTC, HasegawaKota commented on accounts/models.py
> +    )
ないので消しました

2022-07-16 23:09 UTC, HasegawaKota commented on accounts/models.py
> +        return "{} : {}".format(self.follower.username, self.following.username)
直しました

2022-07-16 23:12 UTC, HasegawaKota commented on accounts/views.py
>          return context
今現在、個々のプロフィール情報を直していて、context["tweets_list"]のfilterを変えて表示しているプロフィール本人がツイートした内容だけを表示しようとしているのですがうまくいきません。このuser=self.request.userではなく、表示しているプロフィールの人物にしたいです。何かアドバイスお願い致します。
（文章がわかりにくく申し訳ないです)

2022-07-16 23:13 UTC, HasegawaKota commented on accounts/views.py
> +        )
直しました

2022-07-16 23:13 UTC, HasegawaKota commented on accounts/views.py
> -        return Tweet.objects.all().select_related("user")
直しました

2022-07-16 23:13 UTC, HasegawaKota commented on accounts/views.py
> +        context["tweets_list"] = Tweet.objects.select_related("user")
消しました

2022-07-16 23:13 UTC, HasegawaKota commented on accounts/views.py
> +        ).filter(follower=self.request.user)
消しました

2022-07-16 23:14 UTC, HasegawaKota commented on accounts/views.py
> +            messages.warning(request, "{}は存在しません".format(kwargs["username"]))
直しました

2022-07-16 23:14 UTC, HasegawaKota commented on accounts/views.py
> +                messages.warning(request, "あなたは{}をフォローしました".format(following.username))
直しました

2022-07-16 23:14 UTC, HasegawaKota commented on accounts/views.py
> +            follower = get_object_or_404(User, username=self.request.user.username)
直しました

2022-07-16 23:15 UTC, HasegawaKota commented on accounts/views.py
> +    context_object_name = "following_list"
templateviewをただ何となく今まで使っていました。ありがとうございます！

2022-07-16 23:15 UTC, HasegawaKota commented on accounts/views.py
> +            return HttpResponseRedirect(reverse_lazy("accounts:home"))
直しました

2022-07-16 23:16 UTC, HasegawaKota commented on accounts/views.py
> +        ).filter(following=self.request.user)
まだ直していません

2022-07-16 23:16 UTC, HasegawaKota commented on accounts/tests.py
> +        )
なおしました

2022-07-16 23:17 UTC, HasegawaKota commented on accounts/tests.py
> +        self.assertFalse(FriendShip.objects.filter(following=self.user1).exists())
直しました。そしてフォローしている人をまたフォローした時とアンフォローの人をアンフォローした時のテストもあるべきだと考えてテストコード新たに書きました

2022-07-16 23:18 UTC, HasegawaKota commented on accounts/views.py
> +    template_name = "accounts/follow.html"
まだ直していません

2022-07-16 23:18 UTC, HasegawaKota commented on templates/accounts/follower_list.html
> +<a href="{% url 'accounts:user_profile' pk=user.pk %}" class="btn btn-primary">プロフィール</a>
直しました

2022-07-16 23:18 UTC, HasegawaKota commented on accounts/views.py
> +        return context
ありがとうございます！

2022-07-16 23:52 UTC, HasegawaKota commented on accounts/views.py
> +        ).filter(following=self.request.user)
直しました

2022-07-17 00:20 UTC, HasegawaKota commented on accounts/views.py
> +    template_name = "accounts/follow.html"
直しました

2022-07-17 00:36 UTC, HasegawaKota commented on templates/accounts/home.html
> +  <a href="{% url 'accounts:follow' tweet.user.username %}" class="btn btn-light">{{ tweet.user }}</a>
このif文を使ってフォローとアンフォローに分けるのが出来ていません。以前挑戦したのですがうまくできなくて...
profile画面にフォローとアンフォローのif文を書いてみたのでどこが間違っているかご指摘お願い致します
少しヒント頂けると幸いです

2022-07-17 01:02 UTC, TAK848 commented on accounts/tests.py
> +        self.assertFalse(FriendShip.objects.filter(following=self.user1).exists())
good!!

2022-07-17 01:06 UTC, TAK848 commented on accounts/views.py
> -        return Tweet.objects.all().select_related("user")
前回の点ですが（今気づいたので），paginate_byにより，取得できる投稿が最新の20個までになってしまっているので，
https://medium.com/@kjmczk/django-pagination-7c497995561e
などを参考にhome.htmlにpaginationのリンクをつける，もしくはpaginate_byを削除しましょう！

2022-07-17 01:16 UTC, TAK848 commented on accounts/views.py
>          return context
DetailViewでpk指定したProfileを取得する方法を何個かかいと来ます！（自分でも調べてみてね）

1. `self.kwargs["pk"]`に，urls.pyでpkとした部分の値が入っているので，愚直にそのpkを使いProfileから検索して取得する。（ただしもう一度取得するSQLが発行されるので注意）
2. `print(context)`を`context = super().get_context_data(*args, **kwargs)`の次の行でしてみてください。`context["profile"]`や`context["object"]`としてみると…？
3. `self.object`にDetailViewで取得したprofileはいます（CreateViewとか他でも，単体を扱うようなものでは大体同じように取得できます）

Profileを取得したら，後はonetooneなのでprofile.userとすれば取得できますね！

2022-07-17 01:19 UTC, TAK848 commented on accounts/views.py
> +            messages.warning(request, "{}は存在しません".format(kwargs["username"]))
1. tryの幅が広すぎます
2. 特に理由がなければ`get_object_or_404`を使いましょう！

2022-07-17 01:21 UTC, TAK848 commented on accounts/views.py
> +            return HttpResponseRedirect(reverse_lazy("accounts:home"))
FollowViewに1個残っているので確認お願いします！

2022-07-17 01:23 UTC, TAK848 commented on accounts/views.py
> +        ).filter(following=self.request.user)
good!

2022-07-17 01:25 UTC, TAK848 commented on templates/accounts/follower_list.html
> +<a href="{% url 'accounts:user_profile' pk=user.pk %}" class="btn btn-primary">プロフィール</a>
following_listも直しましょう！（他にもありそうなので，VSCodeで一括検索するなどして確認してみてください！）

2022-07-17 01:26 UTC, TAK848 commented on accounts/views.py
> +    template_name = "accounts/follow.html"
実装OKです！後は分岐だけですね！

2022-07-17 01:32 UTC, TAK848 commented on templates/accounts/home.html
> +  <a href="{% url 'accounts:follow' tweet.user.username %}" class="btn btn-light">{{ tweet.user }}</a>
とりあえずおかしい点:

現状templateで`{% if profile.user in following_list %}`としていますが，
`{{profile.user}}{{following_list}}`としてみるとわかるように，
<img width="790" alt="Screen Shot 2022-07-17 at 10 30 55" src="https://user-images.githubusercontent.com/41906969/179380194-dd6b58f1-dfef-4146-8dc6-c942acc51b50.png">
UserオブジェクトとFriendShipオブジェクトの比較になっていて，inとしてマッチすることがありません。

2022-07-17 01:36 UTC, TAK848 commented on templates/accounts/home.html
> +  <a href="{% url 'accounts:follow' tweet.user.username %}" class="btn btn-light">{{ tweet.user }}</a>
ヒント?
templateであまり複雑なことはできないので，contextとしてフラグをTrueFalseで渡してあげるとかかなーと

2022-07-17 01:39 UTC, TAK848 commented on accounts/tests.py
> +        )
followerの方も…？

2022-07-17 01:43 UTC, TAK848 commented
base.htmlに https://getbootstrap.jp/docs/4.2/components/navbar/#nav を使うなどしてもらえると全ページに綺麗に反映されるのでお願いします！（現状welcome/index.htmlだけにしか反映されていない？）

2022-07-17 02:07 UTC, HasegawaKota commented on accounts/views.py
> +            messages.warning(request, "{}は存在しません".format(kwargs["username"]))
get_object_or_404を使うとexcept以下の内容が反映されないです。exceptの内容を消すとメッセージが表示されなくなり、それは嫌だからこのように直しました。exceptの内容は消すべきということですか？

2022-07-17 04:01 UTC, TAK848 commented on accounts/views.py
> +            messages.warning(request, "{}は存在しません".format(kwargs["username"]))
なるほど，だとしたらtry exceptはokです！すみません！
ですがtry節が長くて見通しが悪いので，できる限り短くなるようにしましょう！

2022-07-17 11:04 UTC, HasegawaKota commented
<img width="538" alt="スクリーンショット 2022-07-17 200247" src="https://user-images.githubusercontent.com/94556033/179395259-e593c752-81a6-48cc-ab41-74559d7d4b0b.png">

2022-07-17 15:18 UTC, HasegawaKota commented
<img width="584" alt="スクリーンショット 2022-07-18 001357" src="https://user-images.githubusercontent.com/94556033/179404846-e8ec49a2-1cbb-4bac-b34b-124b1bab630f.png">
まだフォローしてるときはアンフォロー、アンフォローしているときはフォローのページ遷移のところは直せていません。
そして、友達（第三者）のプロフィールのフォロー一覧、フォロワー一覧を見ると、自分のフォロー一覧とフォロワー一覧が表示されていたため、直しました。

2022-07-17 15:23 UTC, HasegawaKota commented on accounts/views.py
>          return context
アドバイスありがとうございます！無事完了しました

2022-07-17 15:28 UTC, HasegawaKota commented on templates/accounts/home.html
> +  <a href="{% url 'accounts:follow' tweet.user.username %}" class="btn btn-light">{{ tweet.user }}</a>
ここだけまだ直せていません！

2022-07-18 06:31 UTC, HasegawaKota commented on templates/accounts/home.html
> +  <a href="{% url 'accounts:follow' tweet.user.username %}" class="btn btn-light">{{ tweet.user }}</a>
仰って頂いたおかしい点は理解したのですが、contextとしてフラグをTrueFalseの意味がまだあまり分かっておらず、どういうコードを書くべきなのかも理解できていません。もう少しだけアドバイスお願いします。

2022-07-18 08:52 UTC, TAK848 requested changes
返信・コメントしました！確認お願いします！

2022-07-18 08:52 UTC, TAK848 commented on accounts/views.py
> +        user = self.object.user
（細かい話）このままだとまたSQLが発行されるので，
```python
    def get_queryset(self):
        return super().get_queryset().select_related("user")
```
などしてuserも一緒に取得しといてあげるとさらに良いでしょう

2022-07-18 08:52 UTC, TAK848 commented on templates/accounts/home.html
> +  <a href="{% url 'accounts:follow' tweet.user.username %}" class="btn btn-light">{{ tweet.user }}</a>
例えばですが
```python
context['flag'] = True
```
としてあげれば，
`{% if flag %}`のように使えます。

必要なフラグとはどのようなフラグでしょうか？
FriendShipでfolloweeとfollowerの組み合わせがどうなっているものをexi...()でチェックしてあげると...?

2022-07-18 08:52 UTC, TAK848 commented on accounts/views.py
> +        return HttpResponseRedirect(reverse("accounts:home"))
ここだったらtry節は，
```python
following = User.objects.get(username=self.kwargs["username"])
```
だけにしましょう。

例えばですけど
```python
follower = self.request.user
```
まで`try`で囲う必要があるでしょうか？

2022-07-18 08:52 UTC, TAK848 commented on accounts/views.py
> +            # return HttpResponseRedirect(reverse("accounts:home"))
消しましょう！

2022-07-19 02:11 UTC, HasegawaKota commented on accounts/views.py
> +        return HttpResponseRedirect(reverse("accounts:home"))
なんとなくその方が見栄えがきれいだったもので（笑）ありがとうございます

2022-07-19 02:12 UTC, HasegawaKota commented on accounts/views.py
> +        user = self.object.user
def get_queryset(self):
        return super().get_queryset().select_related("user")をFollowingListViewとFollowerListViewにも書いた方がいいでしょうか。ここでもSQLがまた発行されていると思うので

2022-07-19 12:34 UTC, TAK848 commented on accounts/views.py
> +        user = self.object.user
確かにそうですね！
https://qiita.com/fumihiko-hidaka/items/0f619749580da5ad9ce5
みたいに設定して，SQL（データ取得はSELCET）が何回発生しているか実際に試して数えてみると確実です！

2022-07-19 12:36 UTC, TAK848 commented on accounts/views.py
> +        return HttpResponseRedirect(reverse("accounts:home"))
107行目以降，Except節までもtryで囲う必要はありますか？

2022-07-19 12:38 UTC, TAK848 commented on templates/accounts/home.html
> +</p>
全てのページのベースになっている，base.htmlにお願いします

2022-07-19 15:28 UTC, HasegawaKota commented on templates/accounts/home.html
> +</p>
すべてのページに見れるようにしてしまうとサインアップ画面やログイン画面にも反映されてしまうのでそこではテンプレートの継承はしない書き方をした方が良いということですか。

2022-07-19 15:53 UTC, HasegawaKota commented on accounts/views.py
> +        return HttpResponseRedirect(reverse("accounts:home"))
tryがexceptを囲っているってどういうことですか。tryとexceptは同じインデントなので囲っているというのがよくわかりません。申し訳ないのですがなぜこれが間違い？に当たるのかも教えて頂けたら幸いです。ネットでいろいろtryとexceptに関して調べてみいましたがなぜこれが間違い？に当たるのかがわかりませんでした

2022-07-20 00:00 UTC, TAK848 commented on accounts/views.py
> +        ).filter(follower=self.request.user, following=user).exists()
提示した`flag`の命名はあくまで例なので，わかりやすい命名に変えましょう！

2022-07-20 00:00 UTC, TAK848 commented on accounts/views.py
> +            .count()
countしているだけなので，`select_related`は不要です

2022-07-20 00:00 UTC, TAK848 commented on accounts/views.py
> +        return HttpResponseRedirect(reverse("accounts:home"))
説明が不明瞭ですみません…！

まず，try節，except節と言っていたのは，
```python
try:
    try節（今回なら109-120(or121)行目）
except 〇〇:
    except節（今回なら123-124行目）
```
の箇所です。

レビュワー目線の記事ですが，[ここ](https://zenn.dev/515hikaru/articles/review-python-code#try-%E7%AF%80%E3%82%92%E3%82%88%E3%82%8A%E3%82%88%E3%81%8F%E4%BD%BF%E3%81%86)とか参考にしてもらうと良いかもしれません。

言いたいことは，記事の言葉を借りると，
> try 節の中はエラーを起こす可能性のある行のみ入れる。無意味に肥大化させない。

の箇所です。

エラーが出るのが想定されるのって
```python
following = User.objects.get(username=self.kwargs["username"])
```
のみですよね

ですが，try節で110-120行目までも囲うことにより，コードを読んでいてここでもUser.DoesNotExistが出るのかと注意を払うことになってしまいます。
複数人開発においては特に，他の人がコードを読んでも，どこで何が起こる可能性があるかをある程度理解できるように心がけることが大事です（僕もまだまだですが…）。

要するに，try節は例外が予期される行だけ囲うようにできる限り努力しましょう，ということです。

いかがでしょう…？

2022-07-20 00:02 UTC, TAK848 commented on accounts/models.py
> +        User, related_name="following", on_delete=models.CASCADE,)
```suggestion
        User, related_name="following", on_delete=models.CASCADE)
```
上と揃えときましょう

2022-07-20 00:03 UTC, TAK848 commented on accounts/views.py
> +        return HttpResponseRedirect(reverse("accounts:home"))
https://github.com/shinonome-inc/backend-final-assignment-HasegawaKota/pull/4/files#r925049286
にて返信しました！

2022-07-20 08:18 UTC, HasegawaKota commented on accounts/views.py
> +        return HttpResponseRedirect(reverse("accounts:home"))
理解できました！レビュワー目線でいったら仰る通りだと思います。アドバイスありがとうございました！

2022-07-20 09:01 UTC, tak848 commented on accounts/views.py
> +        return HttpResponseRedirect(reverse("accounts:home"))
良いですね！疑問点はどんどん共有してください！

2022-07-20 09:05 UTC, tak848 commented on accounts/views.py
>          )
（参考）bool値は，`is_xx`や`xx_flag`などすると，型の誤解がなくよりわかりやすいです

2022-07-20 09:05 UTC, TAK848 commented on accounts/models.py
> +    )
今回はパスしましょう！

2022-07-20 09:06 UTC, TAK848 approved these changes
お疲れ様でした！
LGTMです！

2022-07-20 09:26 UTC, HasegawaKota commented on accounts/views.py
>          )
一応直しときます。こんなに真摯に対応してくださって誠にありがとうございます！！

2022-07-20 09:47 UTC, TAK848 commented on accounts/views.py
>          )
`xx_is_true`はあまり見ないので，`has_following_connection`とかの方が良いかも！

2022-07-20 09:50 UTC, HasegawaKota commented on accounts/views.py
>          )
了解です

2022-07-20 14:12 UTC, masaya09 commented on accounts/views.py
> +            messages.success(request, f"{following.username}は既にフォローしてるだろ！！！！")
ここのmessagesはsuccessではなくwarningでは？

2022-07-20 14:41 UTC, HasegawaKota commented on accounts/views.py
> +            messages.success(request, f"{following.username}は既にフォローしてるだろ！！！！")
仰る通りです

2022-07-20 21:10 UTC, masaya09 approved these changes
LGTM

2022-07-20 21:10 UTC, merged