'いいね難しい'
shinonome-inc/backend-final-assignment-HasegawaKota pull request #5
Opened 2022-08-14 19:58 UTC by HasegawaKota

2022-08-14 22:55 UTC, shunsuke44 commented
自分の環境で実行してみましたが、特に問題はなさそうでした。
エラーコードを見ると現在では存在しないフィールドでエラーが出てそうなので、マイグレーションがきちんとデータベースに反映されているか調べてみるといいかもしれません。
`python manage.py showmigrations`などを使うとマイグレーションの適用を確認できます。

2022-08-14 23:08 UTC, HasegawaKota commented
<img width="641" alt="スクリーンショット 2022-08-15 080306" src="https://user-images.githubusercontent.com/94556033/184558137-711ada9d-cb5e-464e-bb4e-2bf6dbd17857.png">
ご対応ありがとうございます！確認してみましたが、特に問題はなさそうでした。そして試しにマイグレーションファイルを消して新たにmakemigrations、migrateを試みましたが、改善しませんでした...

2022-08-14 23:34 UTC, shunsuke44 commented
自分の方では問題を再現できなかったので、一度別の場所で該当ブランチをチェックアウトして再度問題が発生するかやってみてください。

2022-08-15 01:47 UTC, TAK848 commented
migrationsファイルの詳しい説明は[Qiita](https://qiita.com/okoppe8/items/c9f8372d5ac9a9679396)や[ここ](https://note.crohaco.net/2018/django-migration/)に任せますが，一度migrateしたmigrationsファイルたちをいじっても反映されません。もしやりたければ，データベースをロールバック（該当migrationsファイルをmigrateする前に戻す）する必要があります。
基本は一度作ったmigrationsはいじらないようにし，ファイルが増えてもそのままにしましょう。

その上で，Shunsukeさんの環境では正常に動くとこからもデータベースに不整合が何か発生してそうなので，`db.sqlite3`を削除（あるいはファイル名変更）してmigrateし直してみてはどうでしょうか？

2022-08-15 21:22 UTC, HasegawaKota commented
上記の問題は無事解決いたしました

2022-08-15 21:23 UTC, HasegawaKota commented
上記の問題は無事解決いたしました。お二人ともありがとうございました。そして大変恐縮ですが、また質問があります。

2022-09-02 18:00 UTC, HasegawaKota commented
頂いたアドバイスを元にhomeでは、一つ一つのツイートがidを持つように直しました。
結果的にいいね、いいね取り消し自体は出来るようになったのですが、肝心のハートの色の変化がつきません笑
detailで作成したものを元にhomeでも作っているのでpkを含むid以外はほとんど同じなのになんでハートの色が変化しないのだろう？と悩んでいます。

何度も質問してしまって大変申し訳ございませんが、どこに着目すれば良いか教えて頂けないでしょうか。

2022-09-02 23:29 UTC, TAK848 reviewed
https://developer.cybozu.io/hc/ja/articles/900000911023-Google-Chrome-開発者ツールのTips集-DOM要素編-#preview-dom-element
とかで，実際リクエストかけると何が変化してるか(/してないか)確かめてみてください！
いじる箇所はあってる…？

2022-09-05 11:48 UTC, HasegawaKota commented
<img width="550" alt="image" src="https://user-images.githubusercontent.com/94556033/188441955-5a236b43-aaa7-432f-96fb-513645a32887.png">

2022-09-06 02:49 UTC, s-nakajima2 approved these changes
特に問題はないと思われるので、二次レビューへ渡します。

コード内にコメントがあって気になったので回答しておくと、`tuple`の中身が1つの時は、マルかっこと区別するために`(hoge, )`のようにカンマが必要です。
[参考](https://note.nkmk.me/python-tuple-single-empty/) 
（既に答えられているものだったら失礼しました）

2022-09-07 04:03 UTC, Akinori13 requested changes
いくつかレビューしました！確認をお願いします！

2022-09-07 04:03 UTC, Akinori13 commented on static/js/api.js
> +
これいらなかったら削除で

2022-09-07 04:03 UTC, Akinori13 commented on tweets/models.py
> +    user = models.ForeignKey(User, on_delete=models.CASCADE)
tweet, userの組み合わせがユニークになるようにしてください

2022-09-07 04:03 UTC, Akinori13 commented on tweets/views.py
> +        context["like_for_tweet_count"] = like_for_tweet_count
これまとめるとダメですか？

2022-09-07 04:03 UTC, Akinori13 commented on tweets/views.py
> +    liked = True
boolが入る場合はis_~がよいです

2022-09-07 04:03 UTC, Akinori13 commented on tweets/views.py
> +    like = Like.objects.filter(user=request.user, tweet=tweet)
404も想定しましょう！

2022-09-07 04:03 UTC, Akinori13 commented on templates/accounts/home.html
> +      console.log(element.dataset.isLiked)
log系は必要なければ削除しちゃいましょう！

2022-09-07 05:53 UTC, HasegawaKota commented on tweets/views.py
> +    liked = True
使ってなかったので消しました

2022-09-08 10:39 UTC, Akinori13 requested changes
２点だけコメントしました！ラストです！

2022-09-08 10:39 UTC, Akinori13 commented on tweets/views.py
> +            context["is_user_liked_for_tweet"] = False
以下だとダメですか？
```suggestion
context["is_user_liked_for_tweet"] = self.object.like_set.filter(user=user).exists()
```

2022-09-08 10:39 UTC, Akinori13 commented on tweets/tests.py
> +        tweet = Tweet.objects.get(contents="ワンピース")
これでいけるはずです！
```suggestion
        tweet = Tweet.objects.create(user=self.user_1, contents="ワンピース")
```

2022-09-08 12:53 UTC, HasegawaKota commented on tweets/views.py
> +            context["is_user_liked_for_tweet"] = False
スマートでかっこいいコードですね

2022-09-08 13:07 UTC, HasegawaKota commented
<img width="540" alt="image" src="https://user-images.githubusercontent.com/94556033/189129785-6843c2ba-aa47-4c7c-89f0-f1c6b4e4fae6.png">

2022-09-09 16:21 UTC, Akinori13 commented on tweets/views.py
> +    like = Like.objects.filter(user=request.user, tweet=tweet)
`get_object_or_404`使ってあげても良かったですね！

2022-09-09 16:21 UTC, Akinori13 commented
LGTM

2022-09-09 16:21 UTC, merged